name: mexi_canje
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0          # Para llamadas API
  provider: ^6.0.5       # Gestión de estado
  shared_preferences: ^2.2.0 # Guardar favoritos
  url_launcher: ^6.1.7   # Abrir sitios web
  cached_network_image: ^3.2.3 # Mostrar imágenes desde URL
  flutter_slidable: ^4.0.0 # Para editar/eliminar favoritos
  supabase_flutter: ^2.8.3
  flutter_dotenv: ^5.2.1
  flutter_animate: ^4.1.1+1
  solar_icons: ^0.0.5
  google_mobile_ads: ^5.3.1
  smooth_corner: ^1.1.1
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.0.0
  fast_cached_network_image: ^1.3.1+3
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.0.0
  

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/empty_list.png
