name: mexi_canje
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5          # Para llamadas API
  provider: ^6.0.5       # Gestión de estado
  shared_preferences: ^2.2.0 # Guardar favoritos
  url_launcher: ^6.1.7   # Abrir sitios web
  cached_network_image: ^3.2.3 # Mostrar imágenes desde URL
  flutter_slidable: ^2.0.0 # Para editar/eliminar favoritos
  supabase_flutter: ^2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/mock_products.json
